apiVersion: v1
kind: Service
metadata:
  name: fruit-encyclopedia
spec:
  selector:
    app: fruit-encyclopedia
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer